FROM node:12

WORKDIR /app/packages
COPY packages/micro micro
COPY packages/entities entities

WORKDIR /app/packages/server
COPY packages/server/package*.json ./
RUN npm ci
COPY packages/server .

RUN npm run build

EXPOSE 3000
CMD [ "npm" , "start"]
