version: '3'
services:
  client:
    build:
      args:
        - VUE_APP_SERVER=http://server:3000

  e2e:
    container_name: cypress
    build:
      context: .
      dockerfile: packages/e2e/Dockerfile
    depends_on:
      - server
      - client
    environment:
      - CYPRESS_BASE_URL=http://client
    volumes:
      - ./packages/e2e/cypress:/app/packages/e2e/cypress
    ipc: host
