version: '3'
services:
  server:
    container_name: server
    build: ./packages/server
    ports:
      - "3000:3000"

  client:
    container_name: client
    build: ./packages/client
    depends_on:
      - server
    environment:
      - SERVER=http://server:3000
    ports:
      - "80:80"

  e2e:
    container_name: cypress
    build: ./packages/e2e
    depends_on:
      - client
    environment:
      - CYPRESS_BASE_URL=http://client
    command: npx cypress run
    volumes:
      - ./packages/e2e/cypress:/app/cypress
