version: '3'
services:
  server:
    build:
      dockerfile: packages/server/Dockerfile.prod

  client:
    build:
      dockerfile: packages/client/Dockerfile.prod
      args:
        - VUE_APP_SERVER=http://localhost:3000
    ports:
      - "80:80"
