version: '3'
services:
  server:
    build:
      dockerfile: packages/server/Dockerfile.dev
    volumes:
      - ./packages/server/src:/app/packages/server/src

  client:
    build:
      dockerfile: packages/client/Dockerfile.dev
    environment:
      - VUE_APP_SERVER=http://localhost:3000
    volumes:
      - ./packages/client/src:/app/packages/client/src
    ports:
      - "80:8080"
