version: '3'
services:
  builder:
    image: builder
    build:
      context: .
      dockerfile: Dockerfile.builder

  server:
    depends_on:
      - builder
    build:
      context: .

  client:
    depends_on:
      - builder
      - server
    build:
      context: .
