version: '3'
services:
  server:
    build:
      dockerfile: packages/server/Dockerfile.dev
    volumes:
      - ./packages/server/src:/app/packages/server/src
      - ./packages/db/dist:/app/packages/db/dist
      - ./packages/entities/dist:/app/packages/entities/dist
      - ./packages/micro/dist:/app/packages/micro/dist
    ports:
      - "3000:3000"

  client:
    build:
      dockerfile: packages/client/Dockerfile.dev
    environment:
      - VUE_APP_SERVER=http://localhost:3000
    volumes:
      - ./packages/client/public:/app/packages/client/public
      - ./packages/client/src:/app/packages/client/src
      - ./packages/entities/dist:/app/packages/entities/dist
      - ./packages/micro/dist:/app/packages/micro/dist
    ports:
      - "80:8080"
