FROM node:12 as build-stage
ARG VUE_APP_SERVER

RUN npm install -g http-server

WORKDIR /app
COPY . .

WORKDIR /app/packages/client
RUN npm ci
ENV VUE_APP_SERVER "$VUE_APP_SERVER"
RUN npm run build

###

FROM nginx:stable-alpine as production-stage
RUN rm /etc/nginx/conf.d/default.conf
COPY packages/client/conf /etc/nginx
COPY --from=build-stage /app/packages/client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
