FROM node:12

WORKDIR /app/packages
COPY packages/entities entities

WORKDIR /app/packages/client
COPY packages/client/package*.json ./
RUN npm ci
COPY packages/client .

EXPOSE 8080
CMD [ "npm", "run", "serve" ]
