version: '3'
services:
  server:
    build:
      dockerfile: packages/server/Dockerfile.prod
    ports:
      - "3000:3000"

  client:
    build:
      dockerfile: packages/client/Dockerfile.prod
      args:
        - VITE_APP_SERVER=http://localhost:3000
    ports:
      - "8080:80"
