version: '3'
services:
  builder:
    image: builder
    build:
      context: .
      dockerfile: Dockerfile.builder

  server:
    container_name: server
    build:
      context: .
      dockerfile: packages/server/Dockerfile.dev
    volumes:
      - ./packages/server/src:/app/packages/server/src
    ports:
      - "3000:3000"

  client:
    container_name: client
    depends_on:
      - server
    build:
      context: .
      dockerfile: packages/client/Dockerfile.dev
    environment:
      - VUE_APP_SERVER=http://localhost:3000
    volumes:
      - ./packages/client/src:/app/packages/client/src
    ports:
      - "80:8080"
