version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server.dev
    volumes:
      - ./packages/server/src:/app/packages/server/src
    ports:
      - "3000:3000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client.dev
    environment:
      - VUE_APP_SERVER=http://localhost:3000
    volumes:
      - ./packages/client/src:/app/packages/client/src
    ports:
      - "80:8080"
