version: '3'
services:
  client:
    container_name: client
    build:
      context: ./packages/client
      dockerfile: Dockerfile-dev
    volumes:
      - ./packages/client:/app
    ports:
      - "8080:8080"
