version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server.prod
    ports:
      - "3000:3000"

  client:
    container_name: client
    build:
      context: .
      dockerfile: Dockerfile.client.prod
      args:
        - VUE_APP_SERVER=http://server:3000
    ports:
      - "80:80"

  e2e:
    container_name: cypress
    build:
      context: .
      dockerfile: Dockerfile.e2e
    depends_on:
      - client
      - server
    environment:
      - CYPRESS_BASE_URL=http://client
    command: npx cypress run
    volumes:
      - ./packages/e2e/cypress:/app/cypress
