name: Test and deploy

on: push

jobs:

  tests_unit:
    name: unit & integration tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: chmod +x ./monoExec.sh ./monoRun.sh
      - run: npm run bootstrap
      - run: npm test

  tests_e2e:
    name: end to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: chmod +x ./e2e.sh ./monoExec.sh ./monoRun.sh
      - run: ./e2e.sh build
      - run: ./e2e.sh run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_KEY }}

  deploy:
    if: ${{ endsWith(github.ref, '/master') }}
    name: deploy to Planethoster
    runs-on: ubuntu-latest
    needs: [tests_unit, tests_e2e]
    steps:
      - uses: actions/checkout@v2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PLANETHOSTER_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: chmod +x ./deploy.sh ./monoExec.sh ./monoRun.sh
      - run: yarn bootstrap
      - run: ./deploy.sh
